### ISSUE TITLE
encoding has a bug

### ISSUE THREAD

**Issue by witwall** [hrbrmstr/filemagic#2] opened 2016-09-18 18:09 UTC
An UTF-8 Unicode (with BOM) text is just utf-8 in encoding, but under Windows, utf-8 and utf-8-bom are different.

btw, I have compiled a static file.exe (version 5.28)

and I can not unzip magic.mgc.zip under Windows

**Comment by hrbrmstr** [comment] 2016-09-18 18:42
It does not have a bug and if it was, you'd have to take it up with the folks who make the `file` utility (where `libmagic` is embedded and where your `file.exe` comes from) since I only use the data that comes back from the utility or the library.

On my Windows 10 system:

```
library(wand)

str(incant("stop_times.txt"))
## Classes ‘tbl_df’, ‘tbl’ and 'data.frame': 1 obs. of  5 variables:
##  $ file       : chr "stop_times.txt"
##  $ mime_type  : chr "text/plain"
##  $ encoding   : chr "utf-8"
##  $ description: chr "UTF-8 Unicode (with BOM) text, with CRLF line terminators"
##  $ extensions :List of 1
##   ..$ : chr  "conf" "def" "in" "ini" ...

str(incant("stops.txt"))
## Classes ‘tbl_df’, ‘tbl’ and 'data.frame': 1 obs. of  5 variables:
##  $ file       : chr "stops.txt"
##  $ mime_type  : chr "text/plain"
##  $ encoding   : chr "utf-8"
##  $ description: chr "UTF-8 Unicode text, with CRLF line terminators"
##  $ extensions :List of 1
##   ..$ : chr  "conf" "def" "in" "ini" ...
```

So, you do indeed get BOM info if you look at the whole object.

You will also note that the package highly suggests installing Rtools for Windows and using it's `file.exe` (I believe you need to put the Rtools bin dir on the `PATH`).

As far as the ZIP files go:

```
c:\d\wand\inst\extdata\db\new>dir
 Volume in drive C has no label.
 Volume Serial Number is 986C-9C35

 Directory of c:\d\wand\inst\extdata\db\new

09/18/2016  11:38 AM    <DIR>          .
09/18/2016  11:38 AM    <DIR>          ..
09/18/2016  11:37 AM           254,930 magic.mgc.zip
               1 File(s)        254,930 bytes
               2 Dir(s)  42,012,917,760 bytes free

c:\d\wand\inst\extdata\db\new>unzip magic.mgc.zip
Archive:  magic.mgc.zip
  inflating: magic.mgc

c:\d\wand\inst\extdata\db\new>dir
 Volume in drive C has no label.
 Volume Serial Number is 986C-9C35

 Directory of c:\d\wand\inst\extdata\db\new

09/18/2016  11:38 AM    <DIR>          .
09/18/2016  11:38 AM    <DIR>          ..
06/13/2016  04:44 PM         4,280,016 magic.mgc
09/18/2016  11:37 AM           254,930 magic.mgc.zip
               2 File(s)      4,534,946 bytes
               2 Dir(s)  42,008,584,192 bytes free

c:\d\wand\inst\extdata\db\new>
```

So, I'm not really sure what the issue is. Unless you can provide something tangible I'm going to have to close it.

**Comment by witwall** [comment] 2016-09-18 21:55
test with 

``` R
devtools::install_github("hrbrmstr/wand")
```

and works now.

**Closed as completed** 2019-09-26 09:46 UTC
